name: Check/Format/Test Rust
on:
  push: { branches: main }
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["cli", "lib", "gui/src-tauri"] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Caching
        uses: Swatinem/rust-cache@v2

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "ci: format using rustfmt"

      - name: install dependencies
        if: matrix.dir == 'gui/src-tauri'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run cargo check
        working-directory: ${{ matrix.dir }}
        run: cargo check --all-features

      - name: Run cargo test
        working-directory: ${{ matrix.dir }}
        run: cargo test --all-features
